### ISSUE TITLE
Creating custom columns in admin view

### ISSUE THREAD

**Issue by leoacosta** [devinsays/team-post-type#4]
Hi Devin,

Thanks for this great resource. Just had a quick question for you...

How would one create a custom column, say to expose the custom post type ID. I want this to show in the columns view to make it easier for users to know what ID's they need to exclude.

Would appreciate your thoughts, thanks again.

Leo

**Comment by devinsays** [comment]
Hi @leoacosta. You can look at another plugin of mine. This one adds a custom column to display a thumbnail image, but the idea is similar: https://github.com/devinsays/portfolio-post-type/blob/develop/includes/class-portfolio-post-type-admin.php#L43

**Comment by leoacosta** [comment]
Thanks Devin, appreciate it!

**Comment by leoacosta** [comment]
Hi @devinsays,

Took a look at the link you mentioned above, got the thumbnails showing, but I also wanted to add the custom post ID right next to it in a separate column. I'm still learning so this is a bit of a head scratcher for me...can you suggest how to go about doing this?

Also, for some reason I am getting duplicate thumbnails showing, not sure why this is happening...

Thanks,

Leo
